### ISSUE TITLE
[Enhancement] Overall Process Enhancement

### ISSUE THREAD

**Issue by sferich888** [edseymour/pvc-transfer#2]
While you would keep the overall flow: 

- Create a new PVC using the preferred storage backend
- Shutdown app (scale replicas to zero) (moves to optional)
- Run sync process job
- Edit Pod specs to use new PVC
- Scale app back up (again moves to optional)

The steps in the 'Run sync process job', don't have to start with 'build the rsync image, needed to run this process '. 

In short if you use the 'cli' image that is shipped with the 4.x payload, you could build the job spec so that it looks like: 

```
      spec:
        containers:
        - name: cli
          image: cli
          command: ["oc", "rsync", "${SRC_POD}:${SRC_PATH}", "/dest"]
          volumeMounts:
          - name: destination
            mountPath: /dest
        restartPolicy: OnFailure 
        volumes:
        - name: destination
          persistentVolumeClaim:
            claimName: ${DEST_PVC}
```

This has the added benefit that, you don't need to scale down the pod, because you can leave the pod up while the rsync happens. 
 - Note: because your using the cli image and (depending on SCC bindings) you could also automate the editing of the pod specs as additional commands. 

This might be something you want to explore or consider (as an enhancement to what you have).
